// Generated by Haxe 4.3.1
#include <hxcpp.h>

namespace hx {
const char *__hxcpp_all_files[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"?",
"HelloWorld.hx",
#endif
 0 };

const char *__hxcpp_all_files_fullpath[] = {
#ifdef HXCPP_DEBUGGER
"/usr/share/haxe/std/cpp/_std/Std.hx",
"/usr/share/haxe/std/cpp/_std/haxe/Log.hx",
"/home/sugeodj/Developer/Languages/haxe/hello/?",
"/home/sugeodj/Developer/Languages/haxe/hello/HelloWorld.hx",
#endif
 0 };

const char *__hxcpp_all_classes[] = {
#ifdef HXCPP_DEBUGGER
"HelloWorld",
"Std",
"haxe.Log",
#endif
 0 };
} // namespace hx
void __files__boot() { __hxcpp_set_debugger_info(::hx::__hxcpp_all_classes, ::hx::__hxcpp_all_files_fullpath); }
