// Generated by Haxe 4.3.1
#include <hxcpp.h>

#ifndef INCLUDED_HelloWorld
#include <HelloWorld.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_f236767cf17b6b76_3_main,"HelloWorld","main",0x5383b167,"HelloWorld.main","HelloWorld.hx",3,0x00bb8cbe)

void HelloWorld_obj::__construct() { }

Dynamic HelloWorld_obj::__CreateEmpty() { return new HelloWorld_obj; }

void *HelloWorld_obj::_hx_vtable = 0;

Dynamic HelloWorld_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< HelloWorld_obj > _hx_result = new HelloWorld_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool HelloWorld_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x14a99f24;
}

void HelloWorld_obj::main(){
            	HX_STACKFRAME(&_hx_pos_f236767cf17b6b76_3_main)
HXDLIN(   3)		::haxe::Log_obj::trace(HX_("Hello World",84,f6,db,6f),::hx::SourceInfo(HX_("HelloWorld.hx",be,8c,bb,00),3,HX_("HelloWorld",00,76,b5,bd),HX_("main",39,38,56,48)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(HelloWorld_obj,main,(void))


HelloWorld_obj::HelloWorld_obj()
{
}

bool HelloWorld_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *HelloWorld_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *HelloWorld_obj_sStaticStorageInfo = 0;
#endif

::hx::Class HelloWorld_obj::__mClass;

static ::String HelloWorld_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	::String(null())
};

void HelloWorld_obj::__register()
{
	HelloWorld_obj _hx_dummy;
	HelloWorld_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("HelloWorld",00,76,b5,bd);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &HelloWorld_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(HelloWorld_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< HelloWorld_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = HelloWorld_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = HelloWorld_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

