// Generated by Haxe 4.3.1
#ifndef INCLUDED_HelloWorld
#define INCLUDED_HelloWorld

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(HelloWorld)



class HXCPP_CLASS_ATTRIBUTES HelloWorld_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef HelloWorld_obj OBJ_;
		HelloWorld_obj();

	public:
		enum { _hx_ClassId = 0x14a99f24 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="HelloWorld")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"HelloWorld"); }

		inline static ::hx::ObjectPtr< HelloWorld_obj > __new() {
			::hx::ObjectPtr< HelloWorld_obj > __this = new HelloWorld_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< HelloWorld_obj > __alloc(::hx::Ctx *_hx_ctx) {
			HelloWorld_obj *__this = (HelloWorld_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(HelloWorld_obj), false, "HelloWorld"));
			*(void **)__this = HelloWorld_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~HelloWorld_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("HelloWorld",00,76,b5,bd); }

		static void main();
		static ::Dynamic main_dyn();

};


#endif /* INCLUDED_HelloWorld */ 
